api = "0.7"

[buildpack]
  description = "A buildpack for installing the appropriate MRI version for an app"
  homepage = "https://github.com/paketo-buildpacks/mri"
  id = "paketo-buildpacks/mri"
  keywords = ["ruby", "mri"]
  name = "Paketo Buildpack for MRI"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/mri/blob/main/LICENSE"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
  [metadata.default-versions]
    ruby = "3.4.*"

  [[metadata.dependency-constraints]]
    constraint = "3.2.*"
    id = "ruby"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "3.3.*"
    id = "ruby"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "3.4.*"
    id = "ruby"
    patches = 2

  [[metadata.dependency-constraints]]
    constraint = "4.0.*"
    id = "ruby"
    patches = 2

[[stacks]]
  id = "io.buildpacks.stacks.jammy"

[[stacks]]
  id = "io.buildpacks.stacks.noble"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
