name: Access Docker On ARM64

on:
  workflow_dispatch: {}
# pull and run the ARM64 Full build stack
# https://medium.com/oracledevs/run-always-free-docker-container-on-oracle-cloud-infrastructure-c88e36b65610
# The docker container is exposed to the internet
# In a separate step, run the binary compilation code
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssg
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker pull paketobuildpacks/build:tiny
          sudo docker run paketobuildpacks/build:tiny ls -al
