name: Skopeo check

on:
  workflow_dispatch: {}

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install crane
      run: |
        mkdir -p "${HOME}"/bin
        echo "${HOME}/bin" >> "${GITHUB_PATH}"

        VERSION=$(curl -s "https://api.github.com/repos/google/go-containerregistry/releases/latest" | jq -r '.tag_name')
        OS=Linux
        ARCH=x86_64
        curl -sL "https://github.com/google/go-containerregistry/releases/download/${VERSION}/go-containerregistry_${OS}_${ARCH}.tar.gz" > go-containerregistry.tar.gz

        tar -zxvf go-containerregistry.tar.gz -C "${HOME}/bin" crane
        chmod +x "${HOME}/bin/crane"
    - name: crane check
      run: |
        which crane
        crane version
