name: Skopeo check

on:
  workflow_dispatch: {}

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: skopeo check
      run: |
        skopeo --version
        sudo apt-get update
        sudo apt-get -y upgrade skopeo
        skopeo --version
